// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjaBTruTplHtr6OGoXdc4FVK3wcTXsoZg',
    appId: '1:91978557269:web:a507043f2ee06ad205b1dc',
    messagingSenderId: '91978557269',
    projectId: 'floorbot-15097',
    authDomain: 'floorbot-15097.firebaseapp.com',
    storageBucket: 'floorbot-15097.firebasestorage.app',
    measurementId: 'G-11WQHZJWS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ4pH6209xNi9ywNtzNg4GsplWW6Ye6B0',
    appId: '1:91978557269:android:d074f1e7ce1cf5b405b1dc',
    messagingSenderId: '91978557269',
    projectId: 'floorbot-15097',
    storageBucket: 'floorbot-15097.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR3EZaLego4lJUsZQ9dI53v8Y9zK3hFPE',
    appId: '1:91978557269:ios:ab5f00359b4d381a05b1dc',
    messagingSenderId: '91978557269',
    projectId: 'floorbot-15097',
    storageBucket: 'floorbot-15097.firebasestorage.app',
    iosBundleId: 'com.example.floorBotMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR3EZaLego4lJUsZQ9dI53v8Y9zK3hFPE',
    appId: '1:91978557269:ios:ab5f00359b4d381a05b1dc',
    messagingSenderId: '91978557269',
    projectId: 'floorbot-15097',
    storageBucket: 'floorbot-15097.firebasestorage.app',
    iosBundleId: 'com.example.floorBotMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjaBTruTplHtr6OGoXdc4FVK3wcTXsoZg',
    appId: '1:91978557269:web:9fa26dbf582434b805b1dc',
    messagingSenderId: '91978557269',
    projectId: 'floorbot-15097',
    authDomain: 'floorbot-15097.firebaseapp.com',
    storageBucket: 'floorbot-15097.firebasestorage.app',
    measurementId: 'G-0QD9NP7ZY4',
  );
}
